# Generated by Django 6.0.3 on 2026-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_photos/'),
        ),
    ]
